src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $firstName = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\Column(length: 100)]
    private ?string $email = null;

    #[ORM\Column(length: 100)]
    private ?string $password = null;

    #[ORM\Column]
    private ?int $role = null;

    #[ORM\Column]
    private ?bool $enabled = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?DateTimeInterface $entryDate = null;

    /**
     * @var Collection<int, Task>
     */
    #[ORM\OneToMany(targetEntity: Task::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $tasks;

    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?Contract $contract = null;

    /**
     * @var Collection<int, Project>
     */
    #[ORM\ManyToMany(targetEntity: Project::class, mappedBy: 'users')]
    private Collection $projects;

    public function __construct()
    {
        $this->tasks = new ArrayCollection();
        $this->projects = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): static
    {
        $this->firstName = $firstName ?? '';

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name ?? '';

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email ?? '';

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getRole(): ?int
    {
        return $this->role;
    }

    public function setRole(int $role): static
    {
        $this->role = $role;

        return $this;
    }

    public function isEnabled(): ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): static
    {
        $this->enabled = $enabled;

        return $this;
    }

    public function getEntryDate(): ?DateTimeInterface
    {
        return $this->entryDate;
    }

    public function setEntryDate(?DateTimeInterface $entryDate): static
    {
        $this->entryDate = $entryDate ?? new \DateTime('now');

        return $this;
    }

    public function getInitials(): string
    {
        return $this->firstName[0] . $this->name[0];
    }

    /**
     * @return Collection<int, Task>
     */
    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    public function addTask(Task $task): static
    {
        if (!$this->tasks->contains($task)) {
            $this->tasks->add($task);
            $task->setUser($this);
        }

        return $this;
    }

    public function removeTask(Task $task): static
    {
        if ($this->tasks->removeElement($task)) {
            // set the owning side to null (unless already changed)
            if ($task->getUser() === $this) {
                $task->setUser(null);
            }
        }

        return $this;
    }

    public function getContract(): ?Contract
    {
        return $this->contract;
    }

    public function setContract(?Contract $contract): static
    {
        $this->contract = $contract;

        return $this;
    }

    public function getFullName(): string
    {
        return $this->firstName . ' ' . $this->name;
    }

    /**
     * @return Collection<int, Project>
     */
    public function getProjects(): Collection
    {
        return $this->projects;
    }

    public function addProject(Project $project): static
    {
        if (!$this->projects->contains($project)) {
            $this->projects->add($project);
            $project->addUser($this);
        }

        return $this;
    }

    public function removeProject(Project $project): static
    {
        if ($this->projects->removeElement($project)) {
            $project->removeUser($this);
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getFullName();
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width; initial-scale=1">
    <title>{% block title %}TaskLinker{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="{{ asset('css/style.css') }}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
              integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
              crossorigin="anonymous" referrerpolicy="no-referrer">
        <script src="https://code.jquery.com/jquery-3.7.1.min.js"
                integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet">
    {% endblock %}

    {% block javascripts %}
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
        <script src="{{ asset('js/select.js') }}"></script>
        {% block importmap %}{{ importmap('app') }}{% endblock %}
    {% endblock %}
</head>
<body>
<div id="main-container">
    <nav>
        <a href="/" id="logo">
            <img src="{{ asset('images/logo.png') }}" alt="Logo TaskLinker"/>
        </a>
        <ul id="main-menu">
            <li{% if (app.request.get('_route') starts with 'project') or (app.request.get('_route') starts with 'task') %} class="active"{% endif %}>
                <a href="/">
                    <i class="fa-solid fa-list-check"></i> Projets
                </a>
            </li>
            <li{% if (app.request.get('_route') starts with 'user') %} class="active"{% endif %}>
                <a href="/employes">
                    <i class="fa-regular fa-user"></i> Équipe
                </a>
            </li>
        </ul>
    </nav>

    <main>
        <header>{% block header %}{% endblock %}</header>
        <div id="content">{% block content %}{% endblock %}</div>
    </main>

</div>
</body>
</html>

templates/project-add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau projet - {{ parent() }}{% endblock %}

{% block header %}
    <div id="current-user"></div>
    <div id="title-page">
        <h1>Nouveau projet</h1>
    </div>
{% endblock %}

{% block content %}
    {{ form_start(form) }}
    <div>
        {{ form_row(form.name) }}
    </div>

    <div>
        <label for="projet_employes">Inviter des membres</label>
        <select id="projet_employes" name="projet[employes][]" multiple="multiple">
            {% for user in users %}
                <option value="{{ user.id }}">{{ user.fullname }}</option>
            {% endfor %}
        </select>
    </div>
    <br>
    <button class="button button-submit">Continuer</button>
    {{ form_end(form) }}
{% endblock %}

templates/project.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ project.name }} - TaskLinker{% endblock %}

{% block header %}
    <div id="current-user"></div>
    <div id="title-page">
        <div class="flex-header">
            <h1>{{ project.name }}</h1>
            <div class="user-list">
                {% for user in project.users %}
                    <div class="avatar" title="{{ user.fullname }}">{{ user.initials }}</div>
                {% endfor %}
            </div>
            <a class="button" href="projets/{{ project.id }}/edit">Modifier</a>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div id="tasks-container">
        {% for status in tasks|keys %}
            <div class="task-column">
                <h2>{{ statuses[status] }}</h2>
                <div class="tasks-list">
                    {% for task in tasks[status] %}
                        <a class="task" href="/tache/{{ task.id }}/modifier">
                            <h3>{{ task.title }}</h3>
                            <p>{{ task.description }}</p>
                            <div class="task-infos">
                                <div class="task-deadline">
                                    <i class="fa-regular fa-calendar"></i> {{ task.deadline | date("m/d/Y") }}
                                </div>
                                {% if task.user %}
                                    <div class="mini-user" title="{{ task.user.fullname }}">
                                        {{ task.user.initials }}
                                    </div>
                                {% endif %}
                            </div>
                        </a>
                    {% endfor %}
                    <a href="{{ project.id }}/tache/creer" class="task-add">
                        + Ajouter une tâche
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}